version: '3'

dotenv: ['.env']

env:
  TORCH_CUDA_ARCH_LIST: "7.5+PTX"  # Defining the env here does not work for gsplat. It must be defined inside its Dockerfile.

includes:
  gsplat: 
    taskfile: ./gsplat/Taskfile.yaml
    dir: ./gsplat
  hierarchical-3d-gaussians: 
    taskfile: ./hierarchical-3d-gaussians/Taskfile.yaml
    dir: ./hierarchical-3d-gaussians

tasks:
  default:
    cmd: task --list-all
  
  clone-all:
    desc: Clone all repositories
    cmds:
      - task: gsplat:clone
      - task: hierarchical-3d-gaussians:clone

  build-all:
    desc: Build all Docker images
    cmds:
      - task: gsplat:build
      - task: hierarchical-3d-gaussians:build

  push-all:
    desc: Push to Github Container Registry
    cmds:
      - task: gsplat:push
      - task: hierarchical-3d-gaussians:push

  pull-all:
    desc: Pull all images from Github Container Registry
    cmds:
      - task: gsplat:pull
      - task: hierarchical-3d-gauss:pull

