name: research-gsplat
services:
  gsplat:
    container_name: nerfstudio-gsplat
    stdin_open: true
    tty: true 
    image: ghcr.io/fabulani/nerfstudio-gsplat:1.4.0
    pull_policy: never
    volumes:  # Change to named volumes for production!
      - ${DATA_PATH}:/workspace/gsplat/data
    ports:
      - "8080:8080"
    ipc: host
    command: ["bash"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]