version: "3"

includes:
  common:
    taskfile: ../.templates/Taskfile.common.yaml
    dir: ./
    internal: true

vars:
  # - docker image
  NAME: 3dgsconverter
  VERSION_TAG: 0.2
  REPOSITORIES:
    - ghcr.io/fabulani
  TAGS:
    sh: |
      for repo in {{ range $i, $repo := .REPOSITORIES }}{{ if $i }} {{ end }}"{{ $repo }}"{{ end }}; do
        echo "$repo/{{ .NAME }}:{{ .VERSION_TAG }}"
      done

  # - cloning
  REPO: https://github.com/francescofugazzi/3dgsconverter.git
  REPO_PATH: ./repo
  COMMIT_ID: 37dc41e

tasks:
  default:
    cmd: task --list

  clone:
    desc: Clone {{.NAME}} and checkout {{.COMMIT_ID}}
    cmds:
      - task: common:clone

  build:
    desc: Build and tag image {{ .NAME }}:{{ .VERSION_TAG }}
    cmds:
      - task: common:build

  push:
    desc: Push image to registries {{.REPOSITORIES}}
    cmds:
      - task: common:push

  pull:
    desc: Pull image from registries {{.REPOSITORIES}}
    cmds:
      - task: common:pull

  run:
    desc: Run {{.NAME}}
    cmds:
      - task: common:run
