version: '3'

vars:
  TAG: ghcr.io/fabulani/nerfstudio-gsplat:1.4.0
  REPO_PATH: ./repo
  
env:
  MAX_JOBS: 10
  TORCH_CUDA_ARCH_LIST: "7.5+PTX"  # Defining the env here does not work. It must be defined inside the Dockerfile.

tasks:
  clone:
    desc: Clone gsplat
    vars:
      REPO: https://github.com/nerfstudio-project/gsplat.git
      COMMIT_ID: e86f392
    cmds: 
      - |
        git clone {{.REPO}} {{.REPO_PATH}} --recursive && \
        cd {{.REPO_PATH}} && \
        git checkout {{.COMMIT_ID}}
      - cp docker/requirements.txt {{.REPO_PATH}}/examples/requirements.txt

  build:
    desc: Build gsplat image
    cmd: |
        docker build \
        --build-arg TORCH_CUDA_ARCH_LIST=$TORCH_CUDA_ARCH_LIST \
        -t {{.TAG}} \
        -f ./docker/Dockerfile ./docker

  push:
    desc: Push gsplat image to Github Container Registry
    cmds:
      - docker push {{.TAG}}

  pull:
    desc: Pull gsplat image from Github Container Registry
    cmds:
      - docker pull {{.TAG}}

  run:
    desc: Run gsplat
    cmds:
      - docker compose -f ./docker/docker-compose.yml up -d
      - docker exec -it nerfstudio-gsplat bash