version: '3'

vars:
  TAG: ghcr.io/fabulani/nerfstudio-gsplat:1.4.0
  TAG_BASE: ghcr.io/fabulani/nerfstudio-gsplat-base:1.4.0
  TAG_WORKER: ghcr.io/fabulani/nerfstudio-gsplat-worker:1.4.0
  REPO_PATH: ./repo
  
env:
  MAX_JOBS: 10
  TORCH_CUDA_ARCH_LIST: "7.5+PTX"

tasks:
  clone:
    desc: Clone gsplat
    vars:
      REPO: https://github.com/nerfstudio-project/gsplat.git
    cmds: 
      - git clone {{.REPO}} {{.REPO_PATH}} --recursive
      - cp docker/requirements.txt {{.REPO_PATH}}/examples/requirements.txt

  build:
    desc: Build gsplat base and worker images
    cmds:
      - task: build-base
      - task: build-wheels
      - task: build-worker
  
  build-test:
    cmd: |
        docker build \
        --build-arg TORCH_CUDA_ARCH_LIST=$TORCH_CUDA_ARCH_LIST \
        -t {{.TAG}} \
        -f ./docker/Dockerfile ./docker

  build-base:
    desc: Build gsplat base image
    internal: true
    cmd: |
        docker build \
        -t {{.TAG_BASE}} \
        -f ./docker/gsplat_base.dockerfile ./docker

  build-wheels:
    desc: Build gsplat wheels
    internal: true
    cmd: |
        docker run -t --rm --name nerfstudio-gsplat-wheel \
        --gpus 1 \
        -v "$(pwd)/docker/dist:/workspace/dist" \
        {{.TAG_BASE}} \
        bash -c "
          cd /workspace/gsplat && \
          python3 setup.py sdist bdist_wheel && \
          cd /workspace/fused-ssim && \
          python3 setup.py sdist bdist_wheel && \
          mv /workspace/gsplat/dist/* /workspace/dist/ && \
          mv /workspace/fused-ssim/dist/* /workspace/dist/
        "

  build-worker:
    desc: Build gsplat worker image
    internal: false
    cmd: |
        docker build \
        --build-arg BASE_IMAGE={{.TAG_BASE}} \
        -t {{.TAG_WORKER}} \
        -f ./docker/gsplat_worker.dockerfile ./docker

  push:
    desc: Push gsplat image to Github Container Registry
    cmds:
      - docker push {{.TAG_BASE}}
      - docker push {{.TAG_WORKER}}

  pull:
    desc: Pull gsplat image from Github Container Registry
    cmds:
      - docker pull {{.TAG_BASE}}
      - docker pull {{.TAG_WORKER}}

  run:
    desc: Run gsplat
    cmds:
      - docker compose -f ./docker/docker-compose.yml up -d
      - docker exec -it nerfstudio-gsplat bash