version: '3'

tasks:

  clone:
    desc: Clone gsplat
    vars:
      REPO: https://github.com/nerfstudio-project/gsplat.git
      DEST: ./repo
    cmd: git clone "{{.REPO}}" "{{.DEST}}" --recursive

  build:
    desc: Build gsplat Docker image
    internal: true
    cmd: ./build_image.sh

  push:

  pull: