name: research-nerfstudio
services:
  PROJECT_NAME:
    container_name: nerfstudio  # Must be same as defined in Taskfile
    stdin_open: true
    tty: true 
    image: nerfstudio:1.1.5  # Must be same as defined in Taskfile
    pull_policy: never
    volumes:  
      - ${DATA_PATH}:/workspace/data  # Usually /workspace/data or /workspace/PROJECT_NAME/data
    ports:
      - "7007:7007"  # Change to needed ports
    ipc: host
    command: ["bash"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]