version: '3'

vars:
  TAG: ghcr.io/fabulani/hierarchical-3d-gaussians:latest
  REPO_PATH: ./repo

tasks:
  clone:
    desc: Clone hierarchical-3d-gaussians
    vars:
      REPO: https://github.com/graphdeco-inria/hierarchical-3d-gaussians.git
    cmd: git clone {{.REPO}} {{.REPO_PATH}} --recursive

  build:
    desc: Build hierarchical-3d-gaussians Docker image
    cmd: docker build -f docker/Dockerfile -t {{.TAG}} {{.REPO_PATH}}

  push:
    desc: Push hierarchical-3d-gaussians image to Github Container Registry
    cmd: docker push {{.TAG}}

  pull:
    desc: Pull hierarchical-3d-gaussians image from Github Container Registry
    cmd: docker pull {{.TAG}}
